need to import the module

In [1]:
import numpy as np

In [30]:
arr=np.array([[1,2,8],[4,7,6]])
print(arr)
print(type(arr))

[[1 2 8]
 [4 7 6]]
<class 'numpy.ndarray'>


all funtions of np array

In [8]:
print(arr.size)  #no.of elements in array
print(arr.shape) #this will print (no.of rows,no.of columns)
print(arr.dtype) #data type
print(arr.transpose())
print(arr.ndim) #no.of dimensions
print(arr.max)
print(arr.min)
print(arr.argmax) # returns index of maximum no.
print(np.sum(arr)) #sum of all elements
print(np.sum(arr,axis=1)) #sum of each row axis=0 means sum of each column


6
(2, 3)
int64
[[1 4]
 [2 5]
 [3 6]]
2


more methods in array


In [36]:
print(arr.mean())   # np.method()==Array_name.Method_name()
print(np.sort(arr))
print(np.std(arr))
print(np.log(arr))
print(np.sqrt(arr))

4.666666666666667
[[1 2 8]
 [4 6 7]]
2.5603819159562025
[[0.         0.69314718 2.07944154]
 [1.38629436 1.94591015 1.79175947]]
[[1.         1.41421356 2.82842712]
 [2.         2.64575131 2.44948974]]


In [15]:
nums=np.ones(5) #similarly for np.zeroes and np.empty(2,4) will create empty array
print(nums)
nums2=np.arange(1,11)  #third parameter for skip index
print(nums2)
print(arr.reshape((3,2)))
print(arr.flatten()) #ravel is used for only reference  flatten returns copy of original

[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


Mathematical operations on two matrices/arrays

In [26]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[2,5,2],[1,6,5]])
a3=np.array([[2,2],[1,6],[3,4]])
print(a1+a2)  # np.add(a1,a2)
print(a1-a2)  #np.subtract(a2,a1)
print(a2/a1)
print(a1*a2) # simple multiplication
print(a1@a3) #matrix multiplication
print(a1.dot(a3)) # same as matrix multiplication

[[ 3  7  5]
 [ 5 11 11]]
[[-1 -3  1]
 [ 3 -1  1]]
[[2.         2.5        0.66666667]
 [0.25       1.2        0.83333333]]
[[ 2 10  6]
 [ 4 30 30]]
[[13 26]
 [31 62]]
[[13 26]
 [31 62]]


Random

In [48]:
print(np.random.random(1)) #no.of element is 1
print(np.random.random((2,2)))  # 2*2 matrix
print(np.random.randint(1,11,(3,3))) #range 1 to 10 and 3*3 matrix of integers
print(np.random.rand(2,2)) # float values
print(np.random.randn(2,2)) # negative numbers
print(np.random.choice(nums2)) #choose one element from 1d array

[0.65139875]
[[0.10399171 0.24375472]
 [0.98305434 0.8442851 ]]
[[1 4 9]
 [8 2 7]
 [9 5 5]]
[[0.89319085 0.16912016]
 [0.88315318 0.57504391]]
[[-0.07225979  0.85829111]
 [-0.09432043  0.70120702]]
4


char methods

In [51]:
s1="hello"
s2="vedant"
s3="i am an engineering student"
print(np.char.add(s1,s2))
np.char.split(s3)
np.char.lower(s1) #upper ,replace ,capitalize ,center(print output at center)

hellovedant


array(list(['i', 'am', 'an', 'engineering', 'student']), dtype=object)